Bookstore: styling
HossainAraf/Book-store pull request #6
Opened 2023-09-09 22:40 UTC by HossainAraf

Method implemented:

- Add any missing JSX elements to your project (without adding extra functionality)
-  final design should match Zeplin's design (this includes all elements + the same styling)
-  may use the CSS rules detailed in Zeplin to style the website.

2023-09-09 22:56 UTC, Efiamotu-1 requested changes
Hi @HossainAraf , 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-09 22:56 UTC, Efiamotu-1 commented on src/styles/nav.css
- [ ] The navigation as shown below in the images are inconsistent you are missing the icon to the far right and as well the font color for both the `Books` & `Categories` navigation, please kindly adjust your design appropriately 👍 
- project design
![nv](https://github.com/HossainAraf/Book-store/assets/89055502/9723c39d-7fba-49c0-affd-2b1a872cd7b6)
- your design
![nvv](https://github.com/HossainAraf/Book-store/assets/89055502/dfd07fd5-3bdf-49c9-bb06-b977340bb0a4)

2023-09-09 22:56 UTC, Efiamotu-1 commented on src/styles/book.css
- [ ] Your design for the books card does not match the provided design you have not followed the proper styling as can be seen from the images below, please kindly adjust your projects design to match the provided design template
- [ ] Your webpage is also overflowing the viewport of the users screen this could be as a result of using `fixed width such as px` I would rather suggest you make use of `%` which are responsive to the users screen 👍 ✨ 
- [ ] Take note of the spacing and font color used in the design when making your changes so that you are using the appropriate fonts and colors 👍 
- project design
![nm](https://github.com/HossainAraf/Book-store/assets/89055502/df642c59-fe50-4269-82af-c48005265d4e)
- your design
![nmm](https://github.com/HossainAraf/Book-store/assets/89055502/1a049098-90ae-44ff-882f-bfce7d596b44)

2023-09-11 06:07 UTC, Ibizugbe reviewed
Hi @HossainAraf 👋🏼, 

Considering that you are repeating, and your project wasn't approved, we will require you to work on a fresh branch and open a new pull request.

## Invalid Code Review Request

You have submitted a project, that <EXPLAIN WHY PROJECT IS INVALID>

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-09-11 06:26 UTC, Davidosky007 reviewed
Hi @HossainAraf 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

## Kindly submit another PR for this project since you are repeating the week

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-09-11 13:08 UTC, merged